/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = BaseEvent & (LoggedInEvent | LoggedInEventV2 | LoginFailedEvent);

export interface BaseEvent {
  id: string;
  subject: string;
  eventTime: string;
  [k: string]: unknown;
}
export interface LoggedInEvent {
  eventType: "loggedin";
  dataVersion: "1";
  data: {
    user?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface LoggedInEventV2 {
  eventType: "loggedin";
  dataVersion: "2";
  data: {
    id?: string;
    email?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface LoginFailedEvent {
  eventType: "loginfailed";
  dataVersion: "1";
  data: {
    message?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
