/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = BaseEvent &
  (ContentViewed | FolderCreated | WorkspaceCreated);

export interface BaseEvent {
  id: string;
  subject: string;
  eventTime: string;
  [k: string]: unknown;
}
export interface ContentViewed {
  eventType: "ContentViewed";
  dataVersion: "1";
  data: {
    userId: string;
    contentId: string;
    contentType: "Folder" | "File";
    workspaceId: string;
    error?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface FolderCreated {
  eventType?: "FolderCreated";
  dataVersion?: "1";
  data?: {
    folderId: string;
    /**
     * The workspace that the folder is in
     */
    workspaceId: string;
    title: string;
    /**
     * The user that created the folder
     */
    userId: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface WorkspaceCreated {
  eventType: "WorkspaceCreated";
  dataVersion: "1";
  data: {
    workspaceId: string;
    title: string;
    /**
     * The id of the user that created the workspace
     */
    userId: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
