/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = BaseEvent & (ContentViewEvent | CreateWorkspaceEvent);

export interface BaseEvent {
  id: string;
  subject: string;
  eventTime: string;
  [k: string]: unknown;
}
export interface ContentViewEvent {
  eventType: "ContentView";
  dataVersion: "1";
  data: {
    userId: string;
    contentId: string;
    contentType: "Folder" | "File";
    workspaceId: string;
    error?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface CreateWorkspaceEvent {
  eventType: "CreateWorkspace";
  dataVersion: "1";
  data: {
    input: {
      title: string;
      description: string;
      [k: string]: unknown;
    };
    output: {
      id: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
